### ISSUE TITLE
404 page not found for Prefect quest 

### ISSUE THREAD

**Issue by ammarsaf** [afrieirham/freexp#1]
Hi Afrie. The link for quest available for Prefect showed `404 page not found`

https://freexp.dev/project/prefect

**Comment by afrieirham** [comment]
Checked before and got the error, but now it's fine, not sure what's happening. 

![image](https://github.com/afrieirham/freexp/assets/32460534/42e33d96-c9bf-44ba-91d6-dee0ee1c8b00)

**Comment by ammarsaf** [comment]
Alright, its working now.
